[package]
org = "ballerinax"
name = "temporal"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["temporal", "workflow", "orchestration"]
repository = "https://github.com/ballerina-platform/module-ballerinax-temporal"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[dependency]]
org = "ballerina"
name="workflow"
version="0.1.0"
repository="local"

[[platform.java21.dependency]]
path = "../native/build/libs/temporal-native-@project.version@.jar"
groupId = "io.ballerina.stdlib"
artifactId = "temporal-native"
version = "@project.version@"

[[platform.java21.dependency]]
path = "../commons/build/libs/temporal-commons-@project.version@.jar"
groupId = "io.ballerina.stdlib"
artifactId = "temporal-commons"
version = "@project.version@"

[[platform.java21.dependency]]
groupId = "io.temporal"
artifactId = "temporal-sdk"
version = "1.20.0"

[[platform.java21.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-api"
version = "1.7.36"

[[platform.java21.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-simple"
version = "1.7.36"